# ML Flow Tracking Server

In [1]:
import pandas as pd
import mlflow

In [4]:
import mlflow.sklearn
from sklearn.ensemble import RandomForestClassifier

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import mean_squared_error

In [12]:
data_x=pd.read_csv('data/X_train.csv')
data_y=pd.read_csv('data/target.csv')


data=pd.concat([data_x, data_y], axis=1)
data.head()

,Married,Education,CoapplicantIncome,LoanAmount,Credit_History,Loan_Status
0,0.728816,-0.528362,1.369336,2.007739,4.516405e-01,1.0
1,0.728816,-0.528362,-0.202214,-0.552730,4.516405e-01,0.0
2,-1.372089,-0.528362,-0.554487,-0.790913,4.516405e-01,1.0
3,0.728816,-0.528362,-0.554487,-0.874277,4.516405e-01,1.0
4,-1.372089,-0.528362,0.466422,-0.171637,3.177548e-16,1.0

In [13]:
from mlflow.models import infer_signature
from urllib.parse import urlparse

In [14]:
data

,Married,Education,CoapplicantIncome,LoanAmount,Credit_History,Loan_Status
0,0.728816,-0.528362,1.369336,2.007739,4.516405e-01,1.0
1,0.728816,-0.528362,-0.202214,-0.552730,4.516405e-01,0.0
2,-1.372089,-0.528362,-0.554487,-0.790913,4.516405e-01,1.0
3,0.728816,-0.528362,-0.554487,-0.874277,4.516405e-01,1.0
4,-1.372089,-0.528362,0.466422,-0.171637,3.177548e-16,1.0
...,...,...,...,...,...,...
609,NaN,NaN,NaN,NaN,NaN,1.0
610,NaN,NaN,NaN,NaN,NaN,1.0
611,NaN,NaN,NaN,NaN,NaN,1.0
612,NaN,NaN,NaN,NaN,NaN,1.0
613,NaN,NaN,NaN,NaN,NaN,0.0

In [16]:
# Depndent & Independent

X=data.drop('Loan_Status', axis=1)
y=data['Loan_Status']

In [17]:
# Split the data to train & test

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=40)

In [19]:
# Hyperparameter tuning GRidsearch cv

def hyperparameter_tuning(X_train, y_train, param_grid):
    rfc=RandomForestClassifier()
    grid_search=GridSearchCV(rfc, param_grid=param_grid, cv=3, n_jobs=-1, scoring='accuracy')

    # Fit GridSearchCV
    grid_search.fit(X_train, y_train)
    return grid_search

In [25]:
signature=infer_signature(X_train, y_train)

# Define Hyperparamter tuning

param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [None, 10, 20, 30],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'max_features': ['auto', 'sqrt', 'log2']
}

# Start ML Flow experiment 
mlflow.set_experiment('LoanEligibility')
with mlflow.start_run():
    #performing hyperparameter tuning
    grid_search=hyperparameter_tuning(X_train, y_train, param_grid)

    #best model
    best_model=grid_search.best_estimator_

    # Evaluate the model
    y_pred = best_model.predict(X_test)
    mse=mean_squared_error(y_test, y_pred)

    #Log best parameters & metrics
    mlflow.log_param('best n estimators', grid_search.best_params_['n_estimators'])
    mlflow.log_param('best max depth', grid_search.best_params_['max_depth'])
    mlflow.log_param('best min samples split', grid_search.best_params_['min_samples_split'])
    mlflow.log_param('best min samples leaf', grid_search.best_params_['min_samples_leaf'])
    mlflow.log_param('best max features', grid_search.best_params_['max_features'])
    mlflow.log_param('mse', mse)

    #tracking url
    mlflow.set_tracking_uri("http://127.0.0.1:5000")

    tracking_url=urlparse(mlflow.get_tracking_uri()).scheme

    if tracking_url !='file':
        mlflow.sklearn.log_model(best_model, 'model', registered_model_name='Best Model')
    else:
        mlflow.sklearn.log_model(best_model, 'model', signature=signature, )

    print(f'Best parameters: {grid_search.best_params_}')
    print(f'Best mse: {mse}')

c:\Users\ntabjul\Downloads\ML Projects\.venv\Lib\site-packages\sklearn\model_selection\_validation.py:528: FitFailedWarning:
324 fits failed out of a total of 972.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
43 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\ntabjul\Downloads\ML Projects\.venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\ntabjul\Downloads\ML Projects\.venv\Lib\site-packages\sklearn\base.py", line 1382, in wrapper
    estimator._validate_params()
  File "c:\Users\ntabjul\Downloads\ML Projects\.venv\Lib\site-packages\sklearn\base.py", line 436, in _validate_params
    validate_parameter_constraints(
  File "c:\Users\ntabjul\Downloads\ML Projects\.venv\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

--------------------------------------------------------------------------------
281 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\ntabjul\Downloads\ML Projects\.venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\ntabjul\Downloads\ML Projects\.venv\Lib\site-packages\sklearn\base.py", line 1382, in wrapper
    estimator._validate_params()
  File "c:\Users\ntabjul\Downloads\ML Projects\.venv\Lib\site-packages\sklearn\base.py", line 436, in _validate_params
    validate_parameter_constraints(
  File "c:\Users\ntabjul\Downloads\ML Projects\.venv\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
c:\Users\ntabjul\Downloads\ML Projects\.venv\Lib\site-packages\sklearn\model_selection\_search.py:1108: UserWarning: One or more of the test scores are non-finite: [       nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan 0.58246047 0.58243553 0.58858297
 0.61912065 0.60687565 0.61297322 0.62523068 0.61912065 0.61913312
 0.62929573 0.62932066 0.63136565 0.64354831 0.64152826 0.63339817
 0.64154073 0.63748815 0.63750062 0.63338571 0.63746322 0.64155319
 0.63135318 0.63543069 0.64358571 0.64357325 0.63743828 0.63949574
 0.58855803 0.58860791 0.58651304 0.60893311 0.6109781  0.60283555
 0.62928326 0.62523068 0.63134072 0.64152826 0.63337324 0.6394708
 0.62930819 0.63337324 0.63949574 0.63543069 0.63747568 0.63341064
 0.63747568 0.63746322 0.64154073 0.63135318 0.6395082  0.64152826
 0.63336077 0.6456307  0.64358571        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
 0.60892064 0.61095316 0.59672552 0.62121552 0.61504314 0.62521822
 0.62727567 0.61913312 0.62321063 0.62730061 0.63135318 0.63545563
 0.63337324 0.63747568 0.63544316 0.62933313 0.62727567 0.63338571
 0.63746322 0.64359818 0.63745075 0.64565564 0.63949574 0.6395082
 0.63538082 0.63746322 0.63339817 0.60895805 0.60691306 0.60690059
 0.61914559 0.62524315 0.63134072 0.62524315 0.63137812 0.61505561
 0.62525562 0.63136565 0.63342311 0.62727567 0.63543069 0.63543069
 0.62524315 0.63543069 0.63341064 0.6395082  0.6395082  0.63544316
 0.64155319 0.6395082  0.63543069 0.64155319 0.64358571 0.63338571
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan 0.58450546 0.59059055 0.59060302
 0.61912065 0.60893311 0.6170632  0.62725074 0.62728814 0.61711307
 0.63543069 0.62319816 0.64152826 0.63135318 0.63743828 0.63543069
 0.63953314 0.62730061 0.63545563 0.62929573 0.64560577 0.63746322
 0.63952067 0.6456307  0.64359818 0.63338571 0.63135318 0.64358571
 0.582448   0.59266048 0.58247294 0.61503067 0.60690059 0.61503067
 0.62929573 0.62524315 0.62932066 0.6333483  0.63541823 0.63948327
 0.63339817 0.63541823 0.63541823 0.63137812 0.62932066 0.63545563
 0.63543069 0.64156566 0.64767569 0.64359818 0.64154073 0.6395082
 0.64155319 0.63949574 0.6395082         nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
 0.59675046 0.58042795 0.58247294 0.61707566 0.6048556  0.61297322
 0.61508055 0.62524315 0.61912065 0.63136565 0.63338571 0.63541823
 0.63339817 0.62728814 0.63338571 0.61711307 0.62525562 0.63341064
 0.63543069 0.63746322 0.63543069 0.63746322 0.64358571 0.64767569
 0.64358571 0.6456307  0.64358571 0.594693   0.58859544 0.58859544
 0.61703826 0.61503067 0.62112824 0.61708813 0.62932066 0.6231857
 0.62933313 0.62929573 0.63543069 0.62727567 0.63338571 0.63746322
 0.63341064 0.63543069 0.63544316 0.64359818 0.64359818 0.6456307
 0.64155319 0.63747568 0.6395082  0.63544316 0.64152826 0.64359818]
  warnings.warn(
2025/01/25 20:52:31 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
Registered model 'Best Model' already exists. Creating a new version of this model...
2025/01/25 20:52:31 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: Best Model, version 2

Best parameters: {'max_depth': 20, 'max_features': 'log2', 'min_samples_leaf': 4, 'min_samples_split': 2, 'n_estimators': 300}
Best mse: 0.2926829268292683
🏃 View run stately-boar-569 at: http://127.0.0.1:5000/#/experiments/233442084668266576/runs/61fbd0fa06454a01b8e377475989f404
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/233442084668266576

Created version '2' of model 'Best Model'.